### ISSUE TITLE
`recursive: true` in `bump.config.ts` ignored?

### ISSUE THREAD

**Issue by chrisspiegl** [antfu-collective/bumpp#33]
The recursive setting is defined in the config and can be applied (via typescript auto complete) but it is ignored when executing the `bumpp` cli.

## Recursive via `pnpm bumpp -r`

<img width="447" alt="Xnapper-2024-04-24-16 49 04" src="https://github.com/antfu-collective/bumpp/assets/1096384/7fb60127-18a9-4e4d-b15c-2c48828a092c">

## Recursive via `pnpm bumpp` and `recursive: true` in `bump.config.ts`

<img width="506" alt="Xnapper-2024-04-24-16 48 39" src="https://github.com/antfu-collective/bumpp/assets/1096384/53608636-b561-42b3-b539-1cf12fd1b498">

## Expected

The `recursive: true` in the config should work the same way the `-r` cli argument works.

**Comment by hyoban** [comment]
This should be fixed in #30, but not published yet
