### ISSUE TITLE
The `recursive` option is not working in the `bump.config.ts` file.

### ISSUE THREAD

**Issue by gz65555** [antfu-collective/bumpp#41]
### Describe the bug

I specified `recursive: true` in my `bump.config.ts`, but it did not take effect when I ran the `bumpp` command.

I believe the following code(`src/cli/parse-args.ts`) is causing the issue:
```typescript
const parsedArgs: ParsedArgs = {
  ...
  options: await loadBumpConfig({
    ...
    recursive: !!args.recursive,
  }),
};
```
If I don't specify `recursive` options when running `bumpp`, `recursive: false` will overwrite the option in `bump.config.ts`. 

This is not the expected outcome.

### Reproduction

https://github.com/gz65555/monorepo-project

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 88.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 22.6.0 - ~/.nvs/default/bin/node
    Yarn: 1.22.21 - ~/Library/pnpm/yarn
    npm: 10.8.2 - ~/.nvs/default/bin/npm
    pnpm: 9.3.0 - ~/Library/pnpm/pnpm
Browsers:
    Chrome: 127.0.6533.122
    Safari: 17.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Would you like to send a quick PR to fix it? Thanks
