### ISSUE TITLE
[Feature request]: check if the git working tree is clean before bumping, if not, refuse to bump

### ISSUE THREAD

**Issue by litingyes** [antfu-collective/bumpp#43]
### Clear and concise description of the problem

There is a scenario where you forget to commit the changed files before bumping

### Suggested solution

Check if the git working tree is clean before bumping, if not, refuse to bump

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome :)

**Comment by litingyes** [comment]
> PR welcome :)

OK
