### ISSUE TITLE
[Bug Report] v9.9.0 regression, `--execute` command throws `ENOENT` error

### ISSUE THREAD

**Issue by meteorlxy** [antfu-collective/bumpp#62]
### Describe the bug

The command in `--execute` flag is causing `ENOENT` error:

```sh
ℹ Executing script pnpm release:changelog
spawn pnpm release:changelog ENOENT
```

Might be a regression of 780b7cc54cd15122dcd7c174217dd1904504e2a7. Downgrading to 9.8.1 could help.

### Reproduction

Not too much time for a repro for now. Will add one later if it's not easy to reproduce.

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.34 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/Library/Caches/fnm_multishells/90151_1733900218066/bin/node
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/90151_1733900218066/bin/npm
    pnpm: 9.15.0 - ~/Library/Caches/fnm_multishells/90151_1733900218066/bin/pnpm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by YunYouJun** [comment]
Caused by https://github.com/antfu-collective/bumpp/commit/780b7cc#diff-98dd85fb32fd9de446227ad9d0c91df2a4f8ec1d1436b6b294ec11413bf3a0e7R80

I created https://github.com/antfu-collective/bumpp/pull/63 to fix this.
